name: build

on:
  workflow_call:
    inputs:
      go_version:
        required: false
        type: string
        default: ^1
    secrets:
      gh_pat:
        required: false

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "^1.16"
          cache: true
          check-latest: true
      - run: go install golang.org/x/vuln/cmd/govulncheck@latest
      - run: govulncheck ./...
  build:
    strategy:
      matrix:
        go-version: ["^1.16"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      GO111MODULE: "on"
      GH_PAT: ${{ secrets.gh_pat }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "^1.16"
          cache: true
      - name: Download Go modules
        run: go mod download
      - name: Build
        run: go build ./...
      - name: Test
        run: go test ./...
